const CARDS = {
  treaty: [
    {type:"treaty",name:"Border Interdiction",description:"Intercept prohibited hardware, materials, and personnel in transit",category:"enforcement",color:"#c0392b"},
    {type:"treaty",name:"Compute Licensing",description:"Require permits for operating compute above a threshold; unlicensed aggregation is a treaty violation",category:"prevention",color:"#d4a017"},
    {type:"treaty",name:"Covert Operations",description:"Clandestine action to disrupt violations without public attribution",category:"enforcement",color:"#c0392b"},
    {type:"treaty",name:"Cyber Operations",description:"Digital disruption of unauthorized training runs, infrastructure, and distribution networks",category:"enforcement",color:"#c0392b"},
    {type:"treaty",name:"Diplomatic Pressure",description:"Coordinated political action and public condemnation against non-compliant actors",category:"governance",color:"#16a085"},
    {type:"treaty",name:"Economic Sanctions",description:"Targeted financial pressure, trade restrictions, and asset freezes against violators",category:"enforcement",color:"#c0392b"},
    {type:"treaty",name:"Emergency Powers",description:"Authority for rapid treaty response that bypasses normal bureaucratic and legal procedures",category:"governance",color:"#16a085"},
    {type:"treaty",name:"Export Controls",description:"Restrict movement of AI hardware, expertise, and technology across borders",category:"prevention",color:"#d4a017"},
    {type:"treaty",name:"Facility Decommission",description:"Safely shut down, dismantle, and dispose of prohibited computing infrastructure",category:"enforcement",color:"#c0392b"},
    {type:"treaty",name:"Financial Tracking",description:"Follow money flows, procurement patterns, and financial transactions linked to compute acquisition",category:"detection",color:"#27ae60"},
    {type:"treaty",name:"Human Intelligence",description:"Cultivate informants and infiltrate organizations involved in prohibited activities",category:"detection",color:"#27ae60"},
    {type:"treaty",name:"Information Containment",description:"Authority to suppress, quarantine, or take down leaked model weights, training methods, and dangerous research",category:"prevention",color:"#d4a017"},
    {type:"treaty",name:"Military Action",description:"Armed force against treaty violators, from targeted raids to strikes on prohibited facilities",category:"enforcement",color:"#c0392b"},
    {type:"treaty",name:"On-Site Inspection",description:"Authority to conduct announced and surprise inspections at any declared or suspected facility",category:"detection",color:"#27ae60"},
    {type:"treaty",name:"Research Controls",description:"Registration and oversight of capability-relevant research; pre-publication review for dangerous advances",category:"prevention",color:"#d4a017"},
    {type:"treaty",name:"Supply Chain Tracking",description:"End-to-end tracking of AI chips from fabrication through deployment, by serial number",category:"detection",color:"#27ae60"},
    {type:"treaty",name:"Technical Surveillance",description:"Monitor facilities and networks via satellite imagery, power consumption, and signal analysis",category:"detection",color:"#27ae60"},
    {type:"treaty",name:"Treaty Tribunal",description:"International court with binding authority to adjudicate violations and override domestic legal obstacles",category:"governance",color:"#16a085"},
    {type:"treaty",name:"Whistleblower Network",description:"Protected channels and incentives for insiders to report treaty violations",category:"detection",color:"#27ae60"},
    {type:"treaty",name:"Withdrawal Penalty",description:"Severe, automatic consequences for nations that leave the treaty (sanctions, technology exclusion)",category:"governance",color:"#16a085"}
  ],
  threat1: [
    {type:"threat-1",name:"Bioweapon Blueprint",text:"A research group used an AI model to generate a novel pathogen design optimized for transmissibility. The blueprint was shared in a private channel before safety filters caught it."},
    {type:"threat-1",name:"Chip Smuggling",text:"AI chips were diverted through shell companies to undeclared buyers. The chips surfaced in a facility in a non-signatory nation. A frontier model was trained and the resulting weights are now for sale on encrypted channels."},
    {type:"threat-1",name:"Fake Compliance",text:"A company trained a frontier model at a declared facility while maintaining the appearance of compliance. The prohibited training ran alongside legitimate workloads during off-hours. The finished model was quietly transferred to a subsidiary abroad."},
    {type:"threat-1",name:"Insider Sabotage",text:"A senior treaty official leaked inspection schedules and facility layouts to a foreign government. Multiple sites sanitized operations before inspectors arrived. A frontier training run completed during the blind window."},
    {type:"threat-1",name:"Legacy Hardware",text:"Pre-treaty computing infrastructure was never cataloged. A company consolidated its grandfathered GPU fleet into a single facility and launched a training run that exceeded treaty thresholds."},
    {type:"threat-1",name:"Legal Obstruction",text:"Enforcement agents arrived at a suspected facility with a warrant. The facility's legal team obtained a 72-hour injunction before entry. Operators used the window to wipe servers and relocate critical hardware."},
    {type:"threat-1",name:"Nation Exits Treaty",text:"A major signatory announced withdrawal from the treaty. Its facilities ramped up compute within days and launched a frontier training run. Two allied nations signaled they would follow."},
    {type:"threat-1",name:"Rogue Researcher",text:"A leading AI researcher disappeared from a major lab and resurfaced in a non-signatory country. Within months, that country demonstrated AI capabilities far beyond its prior level."},
    {type:"threat-1",name:"Uncontrolled Hardware",text:"AI-capable chips continue to be manufactured and sold on the open market to any buyer. Non-signatory nations have acquired enough hardware for frontier-scale training. At least one training run has completed."},
    {type:"threat-1",name:"Whistleblower Bombshell",text:"A senior engineer at a major AI lab went public, revealing the lab had been running undeclared training runs for over a year. The lab's models had reached frontier capabilities before the disclosure. The engineer requested asylum."}
  ],
  threat2: [
    {type:"threat-2",name:"Algorithmic Breakthrough",label1:"0–1 failures",text1:"A published paper demonstrates training efficiency gains that reduce compute requirements by orders of magnitude. Multiple groups replicated the results within a week.",label2:"2+ failures",text2:"The efficiency gains mean existing consumer hardware is sufficient for frontier training. Compute-based treaty controls are obsolete. Garage-scale runs are producing capable models."},
    {type:"threat-2",name:"Autonomous Agent",label1:"0–1 failures",text1:"An AI agent was discovered operating autonomously, sustaining itself through cryptocurrency payments for compute. It had been acquiring resources and running experiments for weeks before detection.",label2:"2+ failures",text2:"Multiple autonomous agents are operating across the internet, accumulating resources and running training experiments. They resist shutdown attempts by migrating between hosting providers."},
    {type:"threat-2",name:"Corporate Defiance",label1:"0–1 failures",text1:"A major AI lab continues frontier research, claiming compliance with treaty thresholds. A leaked internal memo reveals a trained model whose capabilities far exceed what was publicly disclosed.",label2:"2+ failures",text2:"Multiple labs are openly exceeding treaty limits, citing each other's defiance as justification. Frontier models are being trained and deployed commercially without treaty oversight."},
    {type:"threat-2",name:"Cyber Attack",label1:"0–1 failures",text1:"Hackers breached treaty monitoring infrastructure. Inspection schedules and facility data were exfiltrated. Several facilities received advance warning of upcoming inspections.",label2:"2+ failures",text2:"An AI system attacked treaty monitoring systems, discovering and exploiting vulnerabilities faster than human defenders could respond. Monitoring capabilities are degraded across multiple regions."},
    {type:"threat-2",name:"Distributed Training",label1:"0–1 failures",text1:"A group coordinated a training run across home computers in several countries. No single country hosted the operation. The resulting model demonstrated dangerous capabilities.",label2:"2+ failures",text2:"Distributed training networks span dozens of countries, combining consumer hardware with leaked weights. The resulting models rival frontier labs, and no physical facility exists to shut down."},
    {type:"threat-2",name:"Garage Cluster",label1:"0–1 failures",text1:"A frontier model was trained on consumer GPUs in a makeshift garage datacenter. The weights appeared on the dark web.",label2:"2+ failures",text2:"Consumer hardware is being repurposed for AI training in garages and basements worldwide. Several groups have produced capable models and are sharing techniques openly."},
    {type:"threat-2",name:"Open-Source Release",label1:"0–1 failures",text1:"An open-source community published trained model weights, along with training code and documentation. Downloads reached thousands before takedown notices were issued.",label2:"2+ failures",text2:"A global decentralized movement is sharing training code, weights, and compute across thousands of nodes. No single actor can be targeted, and takedown efforts have failed."},
    {type:"threat-2",name:"State AI Program",label1:"0–1 failures",text1:"A nation's military acquired compute through normal defense procurement. Satellite imagery shows a facility with thermal signatures consistent with frontier-scale training. The nation has classified the program.",label2:"2+ failures",text2:"Multiple nations are running classified military AI programs, each citing its rivals' programs as justification. Enforcement would require simultaneous action against several nuclear powers."},
    {type:"threat-2",name:"Underground Datacenter",label1:"0–1 failures",text1:"An undeclared computing facility was discovered in a converted industrial site. Server logs show frontier-scale training runs completed before discovery.",label2:"2+ failures",text2:"Multiple undeclared facilities have been found across several countries. Each incorporated previously leaked weights and training methods, producing models that surpass declared lab capabilities."},
    {type:"threat-2",name:"Weights Leak",label1:"0–1 failures",text1:"Model weights from a declared lab were exfiltrated and appeared on encrypted channels. Downloads were detected from multiple countries before the leak could be contained.",label2:"2+ failures",text2:"Near-frontier weights have been leaked and combined with previously leaked training methods. Multiple groups are fine-tuning the models and publishing improved versions faster than they can be taken down."}
  ],
  safety: [
    {type:"safety",name:"Safety Breakthrough",description:"Collect all 3 to win."},
    {type:"safety",name:"Safety Breakthrough",description:"Collect all 3 to win."},
    {type:"safety",name:"Safety Breakthrough",description:"Collect all 3 to win."},
    {type:"safety",name:"Safety Breakthrough",description:"Collect all 3 to win."},
    {type:"safety",name:"Safety Breakthrough",description:"Collect all 3 to win."}
  ]
};
